### ISSUE TITLE
Merge AddCountry and CheckMap functionality 

### ISSUE THREAD

**Issue by akorunska** [KvitkaOlexandr/Euro_Diffusion#4]
https://github.com/KvitkaOlexandr/Euro_Diffusion/blob/ca1d9e36225a0006257340bf92437c4489b50557/Euro_diffusion/Europe.cs#L30-L36

Traversing this array in such manner occurs twice. 
Firstly, it gets checked here: https://github.com/KvitkaOlexandr/Euro_Diffusion/blob/ca1d9e36225a0006257340bf92437c4489b50557/Euro_diffusion/Europe.cs#L68-L75
Afterwards, array is filled with 1's for each city on the grid.
How about checking for non-zero values right into `AddCountry` method and adding country in countries list after the loop?

**Comment by OleksandrKvitka** [comment]
Since CheckMap is used in validation and error message is printed in case countries intersect, mergin this two methods together will lead to mashing together logic and validation.
Code duplication can be avodied in case of transferring to error handing while running alrorithm, not prior to it. 
I suggest it should be left as it is.

**Comment by akorunska** [comment]
Fine, I agree it's best not to mix things up for current implementation approach.
